name: Update Image URLs

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정마다 실행

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4

      - name: Run scraper script
        run: |
          python scrape_and_commit.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
